# Generated by Django 5.2.6 on 2025-10-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0002_appointments"),
    ]

    operations = [
        migrations.AddField(
            model_name="labs",
            name="email",
            field=models.EmailField(
                default="karremollatharun@gmai.com", max_length=254
            ),
        ),
    ]
