# Generated by Django 5.2.6 on 2025-10-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0003_labs_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labs",
            name="email",
            field=models.EmailField(
                default="karremollatharun@gmail.com", max_length=254
            ),
        ),
    ]
